
desc "Install dependencies, build for testing"
lane :build_for_testing do |options|
	scan(
		build_for_testing: true,
		clean: true,
		workspace: "ChatApp.xcworkspace",
		devices: ["iPhone 11 (15.5)"],
		scheme: "ChatApp"
	)
	puts "Installed dependencies, built for testing done!"
end

desc "Run tests on compiled app"
lane :run_tests do |options|
	scan(
		test_without_building: true
		workspace: "ChatApp.xcworkspace",
		devices: ["iPhone 11 (15.5)"],
		scheme: "ChatApp"
	)
	puts "Tests on compiled app done!"
end

desc "Install dependencies, build for testing and run the tests"
lane :build_and_test do
	build_for_testing
	run_tests
	puts "Installed dependencies, built for testing and the tests done!"
end
