name: CI
on: [push]
jobs:
    build:
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v2
        - uses: ruby/setup-ruby@v1
          with:
            ruby-version: 2.6
            bundler-cache: true
          env:
            ImageOS: getImageOS()
        - name: Run
          run: bundle exec fastlane build_and_test
